-- ============================================================================
-- RepartoPro — Correo: enviados reales y persistentes (la bandeja de entrada
-- necesitaría conectar una cuenta de correo real vía IMAP, que es una
-- integración distinta — aquí dejamos la tabla lista para cuando se conecte)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.sent_emails (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  sent_by     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  to_email    text NOT NULL,
  subject     text NOT NULL,
  body        text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.sent_emails ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_set_company_id ON public.sent_emails;
CREATE TRIGGER trg_set_company_id BEFORE INSERT ON public.sent_emails
  FOR EACH ROW EXECUTE FUNCTION public.set_company_id_trigger();

DROP POLICY IF EXISTS "sent_emails_select" ON public.sent_emails;
CREATE POLICY "sent_emails_select" ON public.sent_emails FOR SELECT TO authenticated
  USING (company_id = public.get_effective_company_id());

DROP POLICY IF EXISTS "sent_emails_insert" ON public.sent_emails;
CREATE POLICY "sent_emails_insert" ON public.sent_emails FOR INSERT TO authenticated
  WITH CHECK (company_id = public.get_effective_company_id());

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.sent_emails;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Tabla para cuando se conecte una bandeja de entrada real (vía IMAP o
-- reenvío a un webhook) — por ahora se queda vacía intencionadamente.
CREATE TABLE IF NOT EXISTS public.received_emails (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  from_email  text NOT NULL,
  subject     text NOT NULL,
  body        text,
  read        boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.received_emails ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_set_company_id ON public.received_emails;
CREATE TRIGGER trg_set_company_id BEFORE INSERT ON public.received_emails
  FOR EACH ROW EXECUTE FUNCTION public.set_company_id_trigger();

DROP POLICY IF EXISTS "received_emails_select" ON public.received_emails;
CREATE POLICY "received_emails_select" ON public.received_emails FOR SELECT TO authenticated
  USING (company_id = public.get_effective_company_id());

DROP POLICY IF EXISTS "received_emails_update" ON public.received_emails;
CREATE POLICY "received_emails_update" ON public.received_emails FOR UPDATE TO authenticated
  USING (company_id = public.get_effective_company_id())
  WITH CHECK (company_id = public.get_effective_company_id());

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.received_emails;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ✅ FIN
