-- ============================================================================
-- RepartoPro — Documentos reales (con archivo de verdad) + Cuadrantes enviados
-- ============================================================================

-- =========================================================
-- 1. Tabla de documentos
-- =========================================================
CREATE TABLE IF NOT EXISTS public.documents (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id   uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  uploaded_by  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  space        text NOT NULL DEFAULT 'mis', -- 'mis' | 'publicos' | 'internos'
  name         text NOT NULL,
  type         text NOT NULL DEFAULT 'pdf',
  size_label   text,
  file_url     text,
  created_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_set_company_id ON public.documents;
CREATE TRIGGER trg_set_company_id BEFORE INSERT ON public.documents
  FOR EACH ROW EXECUTE FUNCTION public.set_company_id_trigger();

-- Lectura: "mis" solo el propio autor; públicos/internos toda la empresa
DROP POLICY IF EXISTS "documents_select" ON public.documents;
CREATE POLICY "documents_select" ON public.documents FOR SELECT TO authenticated
  USING (
    company_id = public.get_effective_company_id()
    AND (space != 'mis' OR uploaded_by = auth.uid())
  );

DROP POLICY IF EXISTS "documents_insert" ON public.documents;
CREATE POLICY "documents_insert" ON public.documents FOR INSERT TO authenticated
  WITH CHECK (company_id = public.get_effective_company_id());

DROP POLICY IF EXISTS "documents_delete" ON public.documents;
CREATE POLICY "documents_delete" ON public.documents FOR DELETE TO authenticated
  USING (company_id = public.get_effective_company_id() AND uploaded_by = auth.uid());

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.documents;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- =========================================================
-- 2. Storage para los archivos
-- =========================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('documentos', 'documentos', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "documentos_upload" ON storage.objects;
CREATE POLICY "documentos_upload"
  ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'documentos');

DROP POLICY IF EXISTS "documentos_read" ON storage.objects;
CREATE POLICY "documentos_read"
  ON storage.objects FOR SELECT TO public
  USING (bucket_id = 'documentos');

DROP POLICY IF EXISTS "documentos_delete" ON storage.objects;
CREATE POLICY "documentos_delete"
  ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'documentos');

-- =========================================================
-- 3. Cuadrantes enviados (reales, compartidos)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.sent_schedules (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id      uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  week_label      text,
  week_start_date text,
  sent_at         text,
  employees       jsonb NOT NULL DEFAULT '[]',
  created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.sent_schedules ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_set_company_id ON public.sent_schedules;
CREATE TRIGGER trg_set_company_id BEFORE INSERT ON public.sent_schedules
  FOR EACH ROW EXECUTE FUNCTION public.set_company_id_trigger();

DROP POLICY IF EXISTS "sent_schedules_select" ON public.sent_schedules;
CREATE POLICY "sent_schedules_select" ON public.sent_schedules FOR SELECT TO authenticated
  USING (company_id = public.get_effective_company_id());

DROP POLICY IF EXISTS "sent_schedules_insert" ON public.sent_schedules;
CREATE POLICY "sent_schedules_insert" ON public.sent_schedules FOR INSERT TO authenticated
  WITH CHECK (company_id = public.get_effective_company_id());

DROP POLICY IF EXISTS "sent_schedules_delete" ON public.sent_schedules;
CREATE POLICY "sent_schedules_delete" ON public.sent_schedules FOR DELETE TO authenticated
  USING (company_id = public.get_effective_company_id());

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.sent_schedules;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ✅ FIN
