-- ============================================================================
-- RepartoPro — Hoja de Pedidos real (compartida entre dispositivos)
-- ----------------------------------------------------------------------------
-- Antes, toda la hoja (cliente, fecha, productos, cantidades) vivía SOLO en
-- el navegador de quien la editaba — un empleado en su propio móvil nunca
-- veía lo que la empresa escribió. Ahora es una tabla real compartida.
-- Hoja de Ruta se alimenta de esta misma tabla.
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.order_sheet_rows (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  employee    text NOT NULL DEFAULT '',
  date        text NOT NULL DEFAULT '',
  product1    text NOT NULL DEFAULT '',
  cant1       text NOT NULL DEFAULT '',
  product2    text NOT NULL DEFAULT '',
  cant2       text NOT NULL DEFAULT '',
  product3    text NOT NULL DEFAULT '',
  cant3       text NOT NULL DEFAULT '',
  product4    text NOT NULL DEFAULT '',
  cant4       text NOT NULL DEFAULT '',
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.order_sheet_rows ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_set_company_id ON public.order_sheet_rows;
CREATE TRIGGER trg_set_company_id BEFORE INSERT ON public.order_sheet_rows
  FOR EACH ROW EXECUTE FUNCTION public.set_company_id_trigger();

-- Empresa y empleados leen y escriben en la hoja de su empresa; clientes no
DROP POLICY IF EXISTS "order_sheet_rows_select" ON public.order_sheet_rows;
CREATE POLICY "order_sheet_rows_select" ON public.order_sheet_rows FOR SELECT TO authenticated
  USING (company_id = public.get_effective_company_id() AND NOT public.is_cliente_role());

DROP POLICY IF EXISTS "order_sheet_rows_insert" ON public.order_sheet_rows;
CREATE POLICY "order_sheet_rows_insert" ON public.order_sheet_rows FOR INSERT TO authenticated
  WITH CHECK (company_id = public.get_effective_company_id() AND NOT public.is_cliente_role());

DROP POLICY IF EXISTS "order_sheet_rows_update" ON public.order_sheet_rows;
CREATE POLICY "order_sheet_rows_update" ON public.order_sheet_rows FOR UPDATE TO authenticated
  USING (company_id = public.get_effective_company_id() AND NOT public.is_cliente_role())
  WITH CHECK (company_id = public.get_effective_company_id() AND NOT public.is_cliente_role());

DROP POLICY IF EXISTS "order_sheet_rows_delete" ON public.order_sheet_rows;
CREATE POLICY "order_sheet_rows_delete" ON public.order_sheet_rows FOR DELETE TO authenticated
  USING (company_id = public.get_effective_company_id() AND NOT public.is_cliente_role());

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.order_sheet_rows;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ✅ FIN
