-- ============================================================================
-- RepartoPro — Hoja de Ruta real (se alimenta de Hoja de Pedidos real)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.route_sheet_extras (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  source_row_id  bigint REFERENCES public.order_sheet_rows(id) ON DELETE CASCADE,
  product_slot   int NOT NULL,
  price          numeric NOT NULL DEFAULT 0,
  total          numeric NOT NULL DEFAULT 0,
  status         text NOT NULL DEFAULT '',
  iva            text NOT NULL DEFAULT '',
  UNIQUE (source_row_id, product_slot)
);

ALTER TABLE public.route_sheet_extras ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_set_company_id ON public.route_sheet_extras;
CREATE TRIGGER trg_set_company_id BEFORE INSERT ON public.route_sheet_extras
  FOR EACH ROW EXECUTE FUNCTION public.set_company_id_trigger();

DROP POLICY IF EXISTS "route_sheet_extras_select" ON public.route_sheet_extras;
CREATE POLICY "route_sheet_extras_select" ON public.route_sheet_extras FOR SELECT TO authenticated
  USING (company_id = public.get_effective_company_id());

DROP POLICY IF EXISTS "route_sheet_extras_upsert" ON public.route_sheet_extras;
CREATE POLICY "route_sheet_extras_upsert" ON public.route_sheet_extras FOR INSERT TO authenticated
  WITH CHECK (company_id = public.get_effective_company_id());

DROP POLICY IF EXISTS "route_sheet_extras_update" ON public.route_sheet_extras;
CREATE POLICY "route_sheet_extras_update" ON public.route_sheet_extras FOR UPDATE TO authenticated
  USING (company_id = public.get_effective_company_id())
  WITH CHECK (company_id = public.get_effective_company_id());

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.route_sheet_extras;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ✅ FIN
