-- ============================================================================
-- RepartoPro — Hoja de Pedidos: productos en líneas independientes + dirección
-- ----------------------------------------------------------------------------
-- Antes: cada pedido tenía 4 columnas fijas de producto/cantidad en la misma
-- fila. Ahora: cada cliente tiene su propia dirección, y cada producto es
-- una línea independiente — se pueden añadir tantas como haga falta.
-- ============================================================================

-- =========================================================
-- 1. Dirección del cliente
-- =========================================================
ALTER TABLE public.order_sheet_rows ADD COLUMN IF NOT EXISTS address text NOT NULL DEFAULT '';

-- =========================================================
-- 2. Tabla de líneas de producto (una fila = un producto)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.order_sheet_items (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  row_id      bigint NOT NULL REFERENCES public.order_sheet_rows(id) ON DELETE CASCADE,
  product     text NOT NULL DEFAULT '',
  quantity    text NOT NULL DEFAULT '',
  position    int NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.order_sheet_items ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_set_company_id ON public.order_sheet_items;
CREATE TRIGGER trg_set_company_id BEFORE INSERT ON public.order_sheet_items
  FOR EACH ROW EXECUTE FUNCTION public.set_company_id_trigger();

DROP POLICY IF EXISTS "order_sheet_items_select" ON public.order_sheet_items;
CREATE POLICY "order_sheet_items_select" ON public.order_sheet_items FOR SELECT TO authenticated
  USING (company_id = public.get_effective_company_id() AND NOT public.is_cliente_role());

DROP POLICY IF EXISTS "order_sheet_items_insert" ON public.order_sheet_items;
CREATE POLICY "order_sheet_items_insert" ON public.order_sheet_items FOR INSERT TO authenticated
  WITH CHECK (company_id = public.get_effective_company_id() AND NOT public.is_cliente_role());

DROP POLICY IF EXISTS "order_sheet_items_update" ON public.order_sheet_items;
CREATE POLICY "order_sheet_items_update" ON public.order_sheet_items FOR UPDATE TO authenticated
  USING (company_id = public.get_effective_company_id() AND NOT public.is_cliente_role())
  WITH CHECK (company_id = public.get_effective_company_id() AND NOT public.is_cliente_role());

DROP POLICY IF EXISTS "order_sheet_items_delete" ON public.order_sheet_items;
CREATE POLICY "order_sheet_items_delete" ON public.order_sheet_items FOR DELETE TO authenticated
  USING (company_id = public.get_effective_company_id() AND NOT public.is_cliente_role());

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.order_sheet_items;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- =========================================================
-- 3. Migrar los productos que ya existían (columnas fijas) a líneas
-- =========================================================
INSERT INTO public.order_sheet_items (company_id, row_id, product, quantity, position)
SELECT company_id, id, product1, cant1, 1 FROM public.order_sheet_rows WHERE COALESCE(product1, '') <> '' OR COALESCE(cant1, '') <> '';
INSERT INTO public.order_sheet_items (company_id, row_id, product, quantity, position)
SELECT company_id, id, product2, cant2, 2 FROM public.order_sheet_rows WHERE COALESCE(product2, '') <> '' OR COALESCE(cant2, '') <> '';
INSERT INTO public.order_sheet_items (company_id, row_id, product, quantity, position)
SELECT company_id, id, product3, cant3, 3 FROM public.order_sheet_rows WHERE COALESCE(product3, '') <> '' OR COALESCE(cant3, '') <> '';
INSERT INTO public.order_sheet_items (company_id, row_id, product, quantity, position)
SELECT company_id, id, product4, cant4, 4 FROM public.order_sheet_rows WHERE COALESCE(product4, '') <> '' OR COALESCE(cant4, '') <> '';

-- =========================================================
-- 4. Hoja de Ruta ahora enlaza directo a la línea de producto (item),
--    no a "fila + posición 1-4" como antes
-- =========================================================
ALTER TABLE public.route_sheet_extras ADD COLUMN IF NOT EXISTS item_id bigint REFERENCES public.order_sheet_items(id) ON DELETE CASCADE;

DO $$
BEGIN
  ALTER TABLE public.route_sheet_extras DROP CONSTRAINT IF EXISTS route_sheet_extras_source_row_id_product_slot_key;
EXCEPTION WHEN undefined_object THEN NULL;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS route_sheet_extras_item_id_key ON public.route_sheet_extras (item_id) WHERE item_id IS NOT NULL;

-- =========================================================
-- 5. Actualizar create_order_row para aceptar dirección + lista de
--    productos de longitud libre (usado por el formulario y la IA)
-- =========================================================
CREATE OR REPLACE FUNCTION public.create_order_row(
  p_employee text,
  p_date     text,
  p_address  text DEFAULT '',
  p_items    jsonb DEFAULT '[]'::jsonb  -- [{"product": "...", "quantity": "..."}]
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_empresa  boolean;
  v_company     uuid;
  v_new_id      bigint;
  v_employee_id uuid;
  v_item        jsonb;
  v_pos         int := 0;
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN jsonb_build_object('success', false, 'error', 'No autenticado');
  END IF;

  SELECT lower(role) IN ('empresa', 'administrador', 'admin', 'dirección') INTO v_is_empresa
  FROM public.profiles WHERE id = auth.uid();

  IF NOT COALESCE(v_is_empresa, false) THEN
    RETURN jsonb_build_object('success', false, 'error', 'Solo la empresa puede crear pedidos');
  END IF;

  IF p_employee IS NULL OR trim(p_employee) = '' THEN
    RETURN jsonb_build_object('success', false, 'error', 'Falta el nombre del cliente');
  END IF;

  v_company := public.get_effective_company_id();

  INSERT INTO public.order_sheet_rows (company_id, employee, date, address)
  VALUES (v_company, p_employee, COALESCE(p_date, ''), COALESCE(p_address, ''))
  RETURNING id INTO v_new_id;

  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_pos := v_pos + 1;
    INSERT INTO public.order_sheet_items (company_id, row_id, product, quantity, position)
    VALUES (v_company, v_new_id, COALESCE(v_item->>'product', ''), COALESCE(v_item->>'quantity', ''), v_pos);
  END LOOP;

  SELECT id INTO v_employee_id
  FROM public.profiles
  WHERE lower(trim(full_name)) = lower(trim(p_employee))
    AND (company_id = v_company OR id = v_company)
    AND id <> auth.uid()
  LIMIT 1;

  IF v_employee_id IS NOT NULL THEN
    INSERT INTO public.notifications (user_id, title, text, type, read)
    VALUES (v_employee_id, 'Nuevo pedido', 'Se añadió un nuevo pedido a Hoja de Pedidos para ti.', 'order', false);
  END IF;

  RETURN jsonb_build_object('success', true, 'row_id', v_new_id);
END;
$$;

GRANT EXECUTE ON FUNCTION public.create_order_row(text, text, text, jsonb) TO authenticated;

-- ✅ FIN
