-- ============================================================================
-- RepartoPro — Sugerencias reales, historial del Asistente real, gráficos
-- de Hoja de Cálculo reales
-- ============================================================================

-- =========================================================
-- 1. Sugerencias (antes se perdían — iban a un servicio externo bloqueado)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.suggestions (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  sent_by     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  name        text,
  email       text,
  category    text,
  type        text,
  text        text NOT NULL,
  status      text NOT NULL DEFAULT 'nueva',
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.suggestions ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_set_company_id ON public.suggestions;
CREATE TRIGGER trg_set_company_id BEFORE INSERT ON public.suggestions
  FOR EACH ROW EXECUTE FUNCTION public.set_company_id_trigger();

-- Cualquiera de la empresa puede enviar; solo empresa puede leer/gestionar
DROP POLICY IF EXISTS "suggestions_insert" ON public.suggestions;
CREATE POLICY "suggestions_insert" ON public.suggestions FOR INSERT TO authenticated
  WITH CHECK (company_id = public.get_effective_company_id());

DROP POLICY IF EXISTS "suggestions_select" ON public.suggestions;
CREATE POLICY "suggestions_select" ON public.suggestions FOR SELECT TO authenticated
  USING (
    company_id = public.get_effective_company_id()
    AND (NOT public.is_cliente_role() OR sent_by = auth.uid())
  );

DROP POLICY IF EXISTS "suggestions_update" ON public.suggestions;
CREATE POLICY "suggestions_update" ON public.suggestions FOR UPDATE TO authenticated
  USING (company_id = public.get_effective_company_id())
  WITH CHECK (company_id = public.get_effective_company_id());

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.suggestions;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- =========================================================
-- 2. Historial real del Asistente IA (antes eran 6 ejemplos falsos y
--    las conversaciones reales no se guardaban)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.assistant_conversations (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  user_id     uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  title       text NOT NULL,
  query       text NOT NULL,
  response    text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.assistant_conversations ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_set_company_id ON public.assistant_conversations;
CREATE TRIGGER trg_set_company_id BEFORE INSERT ON public.assistant_conversations
  FOR EACH ROW EXECUTE FUNCTION public.set_company_id_trigger();

DROP POLICY IF EXISTS "assistant_conversations_select" ON public.assistant_conversations;
CREATE POLICY "assistant_conversations_select" ON public.assistant_conversations FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "assistant_conversations_insert" ON public.assistant_conversations;
CREATE POLICY "assistant_conversations_insert" ON public.assistant_conversations FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid() AND company_id = public.get_effective_company_id());

DROP POLICY IF EXISTS "assistant_conversations_delete" ON public.assistant_conversations;
CREATE POLICY "assistant_conversations_delete" ON public.assistant_conversations FOR DELETE TO authenticated
  USING (user_id = auth.uid());

-- =========================================================
-- 3. Gráficos de Hoja de Cálculo reales (antes solo en el navegador)
-- =========================================================
CREATE TABLE IF NOT EXISTS public.spreadsheet_charts (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid REFERENCES auth.users(id) ON DELETE CASCADE,
  chart_id    text NOT NULL,
  title       text NOT NULL,
  type        text NOT NULL,
  color       text,
  start_row   int NOT NULL,
  end_row     int NOT NULL,
  label_col   int NOT NULL,
  value_col   int NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, chart_id)
);

ALTER TABLE public.spreadsheet_charts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "spreadsheet_charts_all" ON public.spreadsheet_charts;
CREATE POLICY "spreadsheet_charts_all" ON public.spreadsheet_charts FOR ALL TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.spreadsheet_charts;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- ✅ FIN
